# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Steven D'Anna
tagline:          'My Brain Dump'
description:      'Random tidbits for me to come back to at a later date.  If it helps someone else out in the process, then even better!'
url:              http://stevendanna.com
baseurl:          /

author:
  name:           'Steven D''Anna'
  url:            https://twitter.com/stevendanna

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/sdanna/sdanna.github.io
